version: '3'

services:
    nginx:
      build:
        context: .
        dockerfile: Dockerfile-nginx
      volumes:
          - ./symfony/:/var/www/symfony/
      ports:
        - 8081:80
      networks:
        - symfony
      depends_on:
        - php
    php:
      build:
        context: .
        dockerfile: Dockerfile-php
      volumes:
           - ./symfony/:/var/www/symfony/
      networks:
        - symfony
      depends_on:
        - mysql
    mysql:
      image: mysql:8.2
      restart: unless-stopped
      tty: true
      ports:
        - ${DB_PORT}:3306
      environment:
        MYSQL_ROOT_PASSWORD: 
          ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: 
          ${MYSQL_USER}
        MYSQL_PASSWORD: 
          ${MYSQL_PASSWORD}
        MYSQL_DB: 
          ${MYSQL_DB} 
        MYSQL_HOST:
          ${MYSQL_HOST}
      volumes:
        - mysql-symfony:/var/lib/mysql 
      networks:
        - symfony
volumes:
  mysql-symfony:
networks:
  symfony:

